spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 开发环境（本地）数据库
    url: jdbc:mysql://localhost:3306/fly_admin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root123
  redis:
    # 开发环境（本地）Redis
    host: localhost
    port: 6379
    password: 123456
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

# 开发环境日志级别
logging:
  level:
    root: info
    com.fly: debug
